rhiever/tpot

- .gitignore
- .travis.yml
- ci/.travis_install.sh
- ci/.travis_test.sh
Let's see if this does the job ... I guess there will be some weird stuff to debug in the beginning, but let's see what Travis-CI reports back so that we can debug more efficiently.
So, you'd need to login at https://travis-ci.org via your GitHub account and enable travis for this repo. I can't remember exactly, but there should be an option for testing other branches except master. I'd enable this, make a small change to the repo (best in a new branch that you can delete later) to trigger the first build.
> 1st take on continuous integration via travis

- .travis.yml
- README.md
- ci/.travis_install.sh
Okay, let me fix the travis-ci from pullrequest #15 
From now on, it will be a bit easier to debug it before it's merged since we will be able to see the travis reports. 
- this also adds the tracking of the "build" status to the Readme file that you were asking about
I really don't understand this bug regarding the miniconda installation.
In the previous version, I selected the "latest" Miniconda Linux built from http://repo.continuum.io/miniconda/ (`Miniconda-latest-Linux-x86_64.sh`), which apparently doesn't work for some reason. However, selecting, e.g., `Miniconda-3.9.1-Linux-x86_64.sh` does work.
Anyway, let's see
> travis-miniconda installer fix

- tpot/tpot.py
Cleaning up some style issues.
Question: I didn't want to make any changes to the docstrings because this is a personal taste thing, and I am not sure what you think about it, but what about using standard Python docstrings? Also, the docstrings are not very informative, e.g., if someone uses `help(TPOT)`, there wouldn't be much information on the attributes and methods. I'd recommend to change that, also with respect to a future auto-generated API documentation.
> code cleanup

- .gitignore
- docs/mkdocs.yml
- docs/sources/changelog.md
- docs/sources/contributing.md
- docs/sources/examples/MNIST_Example.md
- docs/sources/examples/Using_TPOT_via_code.md
- docs/sources/examples/Using_TPOT_via_the_command_line.md
- docs/sources/index.md
- docs/sources/installing.md
A first take on the documentation. You can see it live here: http://rasbt.github.io/tpot/
(The documentation is hosted via GitHub Pages, I will delete the gh-pages branches at some point, I just wanted to keep it live as a visual example of how it looks like.)
EDIT: If you decide merging it to take it from here, don't worry, it won't be live under http://rhiever.github.io/tpot/ until you run `mkdocs gh-deploy` from the `docs` subdirectory.
> Documentation template

- tpot/tpot.py
Per #45 , this is a first stab at the four additional feature selection operators. 
Things to note:
- Could use some optimization (caching?)
- Could use some toying around with out-of-bounds parameters (e.g., if num_features < 0 in RFE)
- Terminals for both estimators & scoring functions that plug into the new operators 
- i.e., RFE takes a supervised estimator so I hard-coded in a linear-kernel SVC; likewise Select* takes a scoring function, so I used chi2.
- I think this will be of particular importance for generalizing this to regression tasks.
> Additional Feature Selection operators

- tpot/tpot.py
Two find-and-replaces:
1. Column masking in the exported pipeline wasn't working correctly for me with SelectKBest on a model since the mask was coming through as a numeric but some of the columns were named. Updated `[mask]` -> `.iloc[:, mask]` and it seems to work now, though more testing would be good if it was working as expected on your end.
2. `indeces` -> `indices`
> fixing column masking & typo

- tpot/tpot.py
Another small change -- swapped in `f_classif` for the feature selection processes since `chi2` gets tripped up on negative values in the design matrix.
> swapping f_classif for chi2 to allow negative features

- tests.py
- tpot/tpot.py
Per #43 , this abstracts the shared code between static models into a static method that each model can call. In addition, I built a test for testing all the static models / this new abstract method indirectly, and tweaked the num_trees parameter in random_forest to n_estimators to facilitate testing. 
Potential improvements:
1) Maybe it's just me, but It feels a little odd to call a static function from another static function. Does it make sense to move this method (and perhaps some others) to a utility function module? Either way, is it faster to call this abstract method as a static method inside the class, a class method inside the class, or something else?
2) Is there a more appropriate name for the method?
3) Is there a better place to do the input validation (i.e. if there are …
> Abstract function for the classifier pipeline operators

- .gitignore
- docs/mkdocs.yml
- docs/sources/examples/IRIS_Example.md
- docs/sources/examples/MNIST_Example.md
- docs/sources/examples/Using_TPOT_via_code.md
- tutorials/IRIS.ipynb
- tutorials/MNIST.ipynb
- tutorials/tpot_iris_pipeline.py
- tutorials/tpot_mnist_pipeline.py
- Added IRIS example
- Added the updated exported files
- Modified description of Using_TPOT_via_code 
- Added a tutorial folder with Jupyter notebooks for follow along
examples. Let me know if this is required?
Follow-on work: 
- Need to add more detailed descriptions of fit, score & export. 
- Encountered an error while working on the titanic data set for the examples. Need your input on the same.
> Adding the initial examples

- tpot/tpot.py
Build separate functions for the following steps of `export()`:
-Replace all of the mathematical operators with their results
-Unroll the nested function calls into serial code
Closes issue #44, while awaiting implementation of issue #43
> Break export() into sub-functions

- tpot/export_utils.py
- tpot/tpot.py
- tpot/tpot_export.py
Implements the final part of #44 i.e. 'Replace the function calls with their corresponding Python code'
> Break export() into sub-parts

- .travis.yml
- README.md
- ci/.travis_install.sh
- ci/.travis_test.sh
- setup.py
- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Also includes a test and dependency in `setup.py`.
> Replace scikit GradientBoostingClassifier with XGBClassifier

- docs/mkdocs.yml
- docs/sources/ref_index.md
- docs/sources/reference/pipeline_operators/models/classifiers/ensemble/XGBClassifier.md
- tpot/tpot.py
Replaces the scikit GB classifier with the XGB classifier in the docs.
mkdocs.yml, ref_index.md, and XGBClassifier.md. Also made a minor change in tpot.py.
Don't think so.
This fixes what was discussed in the previous XGBoost PR. #83 
#83 
They are being updated in this PR.
No
> Replace scikit GB with XGB in docs

- tpot/tpot.py
> Add catch-all for evaluation function

- README.md
- docs/sources/documentation/TPOT.md
- docs/sources/examples/Custom_Scoring_Functions.md
- docs/sources/examples/IRIS_Example.md
- docs/sources/examples/MNIST_Example.md
- docs/sources/using.md
- tests.py
- tpot/_version.py
- tpot/export_utils.py
- tpot/tpot.py
- tutorials/IRIS.ipynb
- tutorials/MNIST.ipynb
- tutorials/Titanic_Kaggle.ipynb
> Fixed #92 

- tutorials/Titanic_Kaggle.ipynb
Fixes error in Titanic_Kaggle.ipynb
Titanic_Kaggle.ipynb is not viewable in github
[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]
- Do the docs need to be updated? no
- Does this PR add new (Python) dependencies? no
> Have some JSON errors in Titanic_Kaggle.ipynb

- docs/sources/documentation/pipeline_operators/models/classifiers/ensemble/XGBClassifier.md
- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Closing off the second half of #119 removing n_estimators from XGB operator.
I basically copied change for change from your first merge on this at #122 except that there is no test coverage for theXGBClassifier class (it appears because it is not taken from the `sklearn` package list the other classes are.
I've run `nosetests -s -c` locally  (Python 3 conda environment) and CI should be doing the rest.
This is my first pull request ever so really any and all feedback thoroughly welcome!
I'm interested in learning a bit more about your suggested workflow for doing pull requests:
- The installation instructions for a user were in the documentation (and very clear) but I was wondering what conda environment  you would suggest setting up for development (I would guess installing the `tpot` …
> updated all XGB code for n_estimators removal

- docs/mkdocs.yml
- docs/sources/documentation.md
- docs/sources/documentation/pipeline_operators/kernel_approximation/RBFSampler.md
- tpot/export_utils.py
- tpot/tpot.py
* Added RBFSampler to collection of feature preprocessors
Fixes #124 
Check out the documentation at `documentation/pipeline_operators/kernel_approximation/RBFSampler.md`.
The _rbf function is in tpot.py and start at line 1092
By commenting out most other operators you should be able to force TPOT to make use of the RBFSampler.
No
#124 
Yes and I have updated them.
No.
> Rbf sampler

- docs/sources/contributing.md
Adds more steps to contributing documentation, see issue #134.
Only made changes to contributing.md
I've used `mkdocs serve` to see changes locally
Had to do some rejigging of the text due to the numbered list in that section getting broken up otherwise. Also note that I don't think you've deployed new documentation to Github on your repo since your recent commit on how to use mkdocs.
Solves issue #134.
> added more steps to contributing docs

- tpot/export_utils.py
Begins the long journey of refactoring and cleaning up the export_utils module. Here I've refactored the generate_import_code function so that it treats data as data by placing all import statements for different operators/preprocessors into a dict.
The import code generated should also be much cleaner, as it will transform previous imports of the form:
```python
from module.name import OperatorA
from module.name import OperatorB
```
into:
```python
from module.name import OperatorA, OperatorB
```
And duplicate imports are not possible either
In the export_utils.py module at the generate_import_code function.
I would recommend comparing the import statements in exported pipelines between this codebase and the existing codebase to verify they are equivalent.
No
None
- Do the docs need to …
> Refactored export utils' generate_import_code function

- tpot/export_utils.py
Removes the `RuntimeError` exception that is raised when no import statements are defined for a pipeline operator
Line 164 in `tpot/export_utils.py`
Currently the master branch will throw an exception if an exported pipeline uses any operators that don't require any imports (like `_combine_dfs()`). That behavior can be seen in the existing codebase, and can be tested in the teaearlgraycold/eu_imports_ref codebase to see that it does not persist.
No
No
---
Instead of removing the exception I could alternatively require people to enter blank dicts for operators that do not require import statements, but that seems less preferable.
> Removed incorrect exception raise in import code generation function

- docs/sources/examples/Custom_Scoring_Functions.md
Adds missing definitions of all_classes to `Custom_Scoring_Functions.md`. Copied definition from `_balanced_accuracy()` in `tpot.py`
Review updated documentation version of `Custom_Scoring_Functions.md`.
Review updated documentation version of `Custom_Scoring_Functions.md`.
No.
None.
None.
No.
No.
> Add missing definitions of all_classes

- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Attempts to prevent convergence warnings during calls to _fast_ica.
Also outright hides the warnings if they do occur.
Most changes should be in the _fast_ica method of the TPOT class
It wouldn't really be reasonable to write a test for this issue, but running a couple of datasets through TPOT a few times should show that `UserWarning` events no longer are displayed in stdout.
#148 
No 
No
> Hide UserWarning events about tolerance when using the FastICA operator

- ci/.travis_install.sh
- ci/.travis_test.sh
- docs/mkdocs.yml
- docs/sources/documentation/pipeline_operators/models/classifiers/ensemble/AdaBoost.md
- docs/sources/documentation/pipeline_operators/models/classifiers/ensemble/ExtraTrees.md
- docs/sources/documentation/pipeline_operators/models/classifiers/ensemble/GradientBoostingClassifier.md
- docs/sources/documentation/pipeline_operators/models/classifiers/linear_model/PassiveAggressive.md
- docs/sources/documentation/pipeline_operators/models/classifiers/naive_bayes/BernoulliNB.md
- docs/sources/documentation/pipeline_operators/models/classifiers/naive_bayes/GaussianNB.md
- docs/sources/documentation/pipeline_operators/models/classifiers/naive_bayes/MultinomialNB.md
- docs/sources/documentation/pipeline_operators/models/classifiers/svm/LinearSVC.md
- docs/sources/installing.md
- setup.py
- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Adds 7 new classifiers to TPOT
At the _ada_boost() method in the TPOT class, going all the way down to the _p_aggr() method.
There is also relevant export code and docs that should be checked for an LGTM.
Travis should test the classifiers themselves, but a few pipelines could be made and exported to confirm that the code indeed works.
#128
Yes. I have already updated them.
No.
> New classifiers

- tpot/tpot.py
Prevents the FastICA Sklearn operator from reaching an erroneous print statement by thresh-holding the n_components value.
The _fast_ica method in TPOT
@rhiever, I don't believe you ever said what dataset was causing the warnings you were seeing. I haven't been able to recreate the warning personally, but if you were to run this branch on that dataset you should be able to confirm that the warning is no longer and issue.
#153
> Threshhold n_components in _fast_ica to duplicate the logic of the sklearn

- tpot/tpot.py
Replaces the one call to random.random() in tpot.py with np.random.random().
Because deap still uses std. lib's random, I've left the code for seeding random for now.
By comparing the behavior of `_random_mutation_operator()` across Python 2.7 and 3.X 
#159
> Replace calls to random with np.random

- docs/sources/documentation/pipeline_operators/decomposition/FastICA.md
- docs/sources/documentation/pipeline_operators/decomposition/RandomizedPCA.md
- docs/sources/documentation/pipeline_operators/kernel_approximation/RBFSampler.md
- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Removes the n_components argument from _rbf, _pca, and _fast_ica
With the integrated test suite
#163
> Remove n_components argument from some operators (Fixes #163)

- tests.py
- tpot/export_utils.py
- tpot/tpot.py
Makes it so that when shown as a string pipelines show the input as "input_df" rather than "ARG0"
Running the tests, printing out a pipeline and checking that ARG0 is replaced with input_df
The added logic should be covered by the tests
> Replace ARG0 with input_df in piplelines when serialized

- docs/sources/examples/Custom_Scoring_Functions.md
- docs/sources/using.md
- tests.py
- tpot/operators/base.py
- tpot/operators/classifiers/base.py
- tpot/tpot.py
Addresses #156 to allow for classification metrics from scikit-learn's metrics module to be passed to TPOT as scoring functions, along with keyword arguments for the function. Currently  lumps together scoring functions that require decision functions and prediction probabilities together. 
fit(), _evaluate_individual(), and _train_model_and_predict()
With classification scoring functions from sklearn.metrics
Some of the functions require a classifier's _decision-function_ output in place of a list of predicted classes, and some of the functions require a classifier's _prediction-probabilities_ output. These functions are currently lumped together in consideration -- it is difficult to inspect the input scoring function to see if it requires one or the other (without explicit listing of …
> [WIP] Custom scoring

- tests.py
- tpot/operators/classifiers/gradient_boosting.py
- tpot/operators/selectors/__init__.py
- tpot/operators/selectors/select_from_model.py
- tpot/tpot.py
* Adds the SelectFromModel feature selector, using ExtraTreesClassifiers' feature importances
I'm not sure exactly what min and max should be set on threshold for SelectFromModel. Right now I have it set to be in the range of 0. to 1.0
`tpot/operators/selectors/select_from_model.py`
#212
> Add SelectFromModel feature selector (Fixes #212)

- docs/sources/using.md
- tests.py
- tpot/tpot.py
1. Addresses #238, allowing use for compatible loss/error functions and having TPOT takes the best pipeline when using log_loss. 
2. Uses sklearn's get_scorer function to validate strings passed in a scoring_function are valid (for cross_val_score), and restricts use of custom functions. 
3. Tweaks the instantiator test to reflect the above changes. 
tpot.py:__init__()
tpot.py:fit()
tpot.py:_evaluate_individual()
Making sure that the fitted pipelines 
1. Some scoring functions implemented in sklearn only allow for binary classification, causing pipelines to raise exceptions if the data is multiclass.
2.  `log_loss` needs predict_proba support. This may restrict the classifier operators used in the final pipelines to those that support that functionality. 
#238 
- Do the docs need to be …
> cross_val_score scoring_function support

- tpot/tpot.py
Make TPOT fail gracefully when all pipelines fail to evaluate (issue #236)
From Line 307 in tpot.py
Run the codes with the data in the issue #233 
Just add a 'if' sentence to determine whether all pipelines are failed
The issue #236  links to the issue #233 and issue #234 
No
No
> For issue #236

- ci/.travis_install.sh
- ci/.travis_test.sh
- setup.py
- tpot/base.py
- tpot/operators/classifiers/__init__.py
- tpot/operators/classifiers/xg_boost.py
Adds XGBoost as an optional dependency
* `tpot/operators/classifers/xg_boost.py`
* `tpot/operators/classifiers/__init__.py`
Running TPOT on a machine with xgboost installed and a machine without xgboost installed.
#154 
Yes
Yes
> Add XGBoost as an optional dependency (Fixes #152)

- tpot/base.py
- tpot/decorators.py
Fix a bug in the old time_out function
decorators.py
from sklearn.datasets import load_digits
from sklearn.cross_validation import train_test_split
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
train_size=0.75, test_size=0.25)
tpot = TPOTClassifier(generations=3, population_size=40, verbosity=2,max_eval_time_mins=0.02,random_state=99)
tpot.fit(X_train, y_train)
Timeout will work in but still not support KeyBoardInterrupt in Windows. Any suggestion?
> Fix bugs in timeout in Linux and MacOS

- tpot/base.py
- tpot/decorators.py
Fix the bugs about Ctrl-C crashing Python in Windows OS 
This bugs are related to [scipy.stats installs FORTRAN Control-C handler](https://github.com/ContinuumIO/anaconda-issues/issues/905)
Add new timeout function for windows. This function still use wall time instead of CPU time ( timeout function for Linux and MacOS is CPU time). But now it allow users to use Ctrl+C to interrupt pipeline evaluation and save the best pipeline.
Line 51 in base.py
Line141 in decorators.py
from sklearn.datasets import load_digits
from sklearn.cross_validation import …
> Hot patch for solving the keyboardinterrupt in Windows & New timeout function for Windows OS

- tpot/decorators.py
resource.setrlimit sometimes doesn't respect when runing scikit-learn in macOS. It seems a old issue of python in macOS. So I limited the CPU time-limit function only works in Linux OS while wall time-limit funciton works in MacOS and Windows OS.
Additional link:
http://bugs.python.org/issue17409
http://stackoverflow.com/questions/15633474/python-on-macos-totally-ignoring-rlimit
line 110 in decorators.py
Run these codes below in MacOS (verison 10.11.2 - 10.12.1).It should fail with "Cputime limit exceeded: 24" error message. It will fail randomly!!
But if you try the codes in Linux it will be all right.
```
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import ExtraTreesClassifier
from …
```
> Hot patch of fixing a bug in time limit function in MacOS

- tpot/operators/preprocessors/feat_agg.py
Avoid memory overflow due to possible bugs about "cosine" affinity type in FeatureAgglomeration. No issue with other affinity types.
Use the codes below to reproduce the memory overflow with the dataset in issue #271 
```
from sklearn.cluster import FeatureAgglomeration
import numpy as np
import time
train_data = np.genfromtxt('fold_2_trainFeatVec.csv', delimiter=',')
train_labels= np.genfromtxt('fold_2_trainLabels.csv', delimiter=',')
fa = FeatureAgglomeration(affinity="cosine", linkage="average") # no matter linage ="average" or "complete"
time_start= time.time()
fa.fit(train_data, train_labels) # memory keeping increasing here
time_end = time.time()
print('Time usage:',time_end-time_start)
```
#271
#252
> Remove 'cosine' affinity type from FeatureAgglomeration to avoid memory overflow

- tpot/base.py
- tpot/operators/classifiers/logistic_regression.py
Add sag solver for logistic regression to handle large dataset.
tpot/operators/classifiers/logistic_regression.py
Any TPOT examples
#271
#292
#252
‘sag’ only handle L2 penalty and only works with dual = False. It means dual is False in both l1 and l2 penalty. Thus, no dual argument if sag is added. Is it OK?
> Add sag solver for logistic regression

- tpot/base.py
- tpot/gp_deap.py
In the source codes of [algorithms.eaSimplie](https://github.com/DEAP/deap/blob/master/deap/algorithms.py) in deap, the fitness.values were removed during generating offsprings in each generation by crossover or mutation. So these pipeline generated by crossover and mutation need be evaluated again in the new generation. However, if the diversity of pipelines are limited by customizing used operators. Many duplicated pipelines can be generated over generations. Evaluating the same pipelines is worthless. So in this RP, a list of evaluated individual is added. In each time of pipeline evaluation, the pipeline must be checked first whether it is evaluated before. If so, its fitness scores are assigned with that in previous evaluations. The way can speed up a lot TPOT pipeline optimization …
> Checking duplicated pipeline in TPOT optimization process

- docs/sources/using.md
- tests.py
- tpot/base.py
- tpot/decorators.py
- tpot/driver.py
Hi!  So I made a crack at this after v0.6 appeared to push up, here's what I've got so far:
I'm storing/not-rewriting pop and _hof in the case of a warm_start; I -think- that was the general plan.
I've only made additions to tpot/base.py .  The existing nosetests all seem to run fine, but I feel like I should add some others–I'm not 100% sure what to test in terms of the tpot lifecycle and when the stored variables should exist, so I'd appreciate some guidance on that.  Would it be easier to do in the form of a Pull Request?
Also, I looked at driver.py (is this feature also meant to be accessible from the command line?) and thought I'd add something like this:
``` python
parser.add_argument('--warm-start', action='store', dest='WARM_START', default=False,
choices=[True, False], type=bool, …
```
> adding warm_start functionality by storing  pop and self._hof if desired

- conda_recipes/tpot/meta.yaml
Add a conda recipe for adding TPOT into conda-forge. We need submit a PR at [staged-recipes](https://github.com/conda-forge/staged-recipes) with the recipe (comments is not allowed in the recipe, so I already deleted all the comments) to officially adding TPOT into conda-forge channel.
conda_recipes/tpot/meta.yaml
```
conda config --add channels conda-forge
conda build tpot
```
#165 
Because one dependency, deap, is only available in python 2.7, 3.4 and 3.5 in conda-forge, so the tpot can be only built in conda-forge with these 3 versions of pythons. For better compatibility, a update in recipe of this dependency is needed. Could we submitted another PR for updating deap in conda-forge?
> Adding TPOT into conda-forge

- tests.py
- tpot/base.py
Make TPOT work with sample weights.
Line 527 in base.py
```
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
digits = load_digits()
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target,
train_size=0.10, test_size=0.90)
sample_weight = range(1, len(y_train) + 1) # made-up weights
tpot = TPOTClassifier(generations=5, crossover_rate= 0.5, population_size=20)
tpot.fit(X_train, y_train, sample_weight=sample_weight)
print(tpot.score(X_test, y_test))
```
#310 
I wil add a unit test for this function soon.
> Adding sample_weight argument into tpot.fit()

- tpot/base.py
Add `-1` option in `n_jobs` to use all CPU in one compute node for running TPOT
> Add -1 Option in n_jobs

- tpot/base.py
- tpot/decorators.py
- tpot/gp_deap.py
1. Uses `_pre_test`  to decorate class functions of `TPOTBase` and not only to be called when registering mate/mutate functions. Adds a wrapper around `gp.cxOnePoint(ind1, ind2)` so that the wrapper can be decorated with `_pre_test`. This ensures that operator's arguments are all passed into the decorator, including `self` argument.
2. Adds support for evaluation of both Individual and tuple of Individuals as a result of decorated function.
3. Adds debug printout to show any exceptions inside the decorator. 
- ` _pre_test` function in `decorators.py`
- `_setup_toolbox` in `base.py`
Any TPOT example
#366 
#368
> _pre_test decorator

- docs_sources/installing.md
For Windows OS,, the pywin32 module is required if the Python is NOT installed via Anaconda Python distribution and can be simplify installed with pip command.
This PR is related to the issue #333
> Add documentation about installing pywin32 in windows OS

- tpot/base.py
> Add checks for invalid metrics and invalid dataset

- tpot/decorators.py
`threading.Thread` has no attribute '_stop' in python 2.* in Windows. This PR changes decorators to support old version of python.
This codes have been tested with python2.7 in Windows.
Related Issue #395
> Timeout decorators now works with python 2.* in Windows

- tpot/base.py
- tpot/gp_deap.py
Replace `gp.cxOnePoint` in base.py to make TPOT can reproduce results with a given random seed. This issue is caused by using unordered data structure `set()` when mating two patients. The issue is also posted on [deap repo](https://github.com/DEAP/deap/issues/190)
gp_deap.py
Run any TPOT examples multiple times with a fixed random seed
#392 
[Issue 190 on deap](https://github.com/DEAP/deap/issues/190)
> A patch to replace gp.cxOnePoint for solving the reproducibility issue with a given random seed

- setup.py
- tests.py
- tpot/__init__.py
- tpot/_version.py
- tpot/base.py
- tpot/built_in_operators.py
- tpot/config_classifier.py
- tpot/config_classifier_light.py
- tpot/config_classifier_mdr.py
- tpot/config_regressor.py
- tpot/config_regressor_light.py
- tpot/decorators.py
- tpot/driver.py
- tpot/export_utils.py
- tpot/gp_deap.py
- tpot/gp_types.py
- tpot/metrics.py
- tpot/operator_utils.py
- tpot/tpot.py
* Provides Python code that (for the most part) conforms to PEP8 standards.
- Line length wasn't taken too seriously, although I still tried to stick with 80 characters when reasonable
- The code copied from DEAP wasn't treated as strictly as the rest of the code
* Improves code readability through functional decomposition
> Conform to PEP8 standards

- tpot/base.py
Related issue #429 
Fix a bug casuing issue when reading config dictionary
> A patch for config_dict parameter

- tpot/base.py
A quick change for supporting python dictionary in `config_dict` parameter in interactive mode. 
Related issue is #429
> Restore support for python dictionary in config_dict parameter

- requirements.txt
A quick PR for related issue #433
> Update deap version to 1.0.2 in requirements.txt

- requirements.txt
```
pip install deap==1.0.2
Collecting deap==1.0.2
Could not find a version that satisfies the requirement deap==1.0.2 (from versions: 0.9.1, 0.9.2, 1.0.0rc3, 1.0.0, 1.0.1, 1.0.2.post2)
No matching distribution found for deap==1.0.2
pip install deap==1.0.2.post2
Collecting deap==1.0.2.post2
Installing collected packages: deap
Successfully installed deap-1.0.2
```
So I changed 1.0.2 to 1.0.2.post2
Related issue: #434 #433
> Correct deap version to 1.0.2.post2

- tests.conf
- tests.py
- tpot/base.py
1. Removed python2 uncompliant code (related issue #435 )
2. Add unit tests for `conf_dict` (related issue #429)
> Remove Python2 uncompliant codes

- tests.py
- tpot/base.py
- tpot/driver.py
1. add 7 unit tests  to increase coverage.
2. fix a bug in `_print_args`
2 of tests are based on the demo in #337
> Add 7 unit tests

- ci/.travis_install.sh
- tests.py
- tpot/config_classifier_mdr.py
1. Fix compatibility issue in TPOT MDR with the lastest version (0.4.4) of scikit-MDR
2. Add a unit test for TPOT MDR
Related issue #450
> A hot patch for TPOT MDR for supporting latest version of scikit-MDR

- tests.py
- tpot/base.py
1. Use `sklearn_pipeline_str` instead of `individual_str` (from deap)
2. Add a unit test for this issue.
Note this PR should be merged to master branch.
Related issue #454
> A patch for fixing the issue 454

- tests.py
- tpot/built_in_operators.py
A small update for `ZeroCount` operator:
1. Remove `lambda` function in` ZeroCount` for pickling pipeline
2. Make `ZeroCount` as a subclass of TransformerMixin
3. Add a unit test for `ZeroCount`
Note: this PR should have conflicts with PR #460. Please let me know if #460 is merged then I will rebase this PR to dev branch again.
> Refine ZeroCount

- docs_sources/api.md
- tests.py
- tpot/base.py
Revised attributes based on issue 473 and 474
> For issue 473 and 474

- docs_sources/releases.md
Add release log for version 0.8
Please let me know if I miss something important.
> Release log for version 0.8

- tpot/driver.py
`driver.py` wasn't updated for the release. As support for the CLI driver is low-priority, we can release this with any other fixes in the 0.8.1 release.
> Update the driver for 0.8 release

- tpot/base.py
Slightly refactored the TPOTBase._evaluate_individuals function changing:
- Better legibility. After the introduction of parallelized evaluations of individuals, there was a lot of list-keeping added. This made the function very verbose and made it harder to see from a glance what happened. The rework requires zero list-indexing or sorting and has fewer lists, which hopefully makes it easier to read. Furthermore, some logic used to be delayed (eg. faulty pipelines would only be recorded in the evaluated_individuals_ dict way after they were found to be faulty, operator_count would first be calculated, but then quickly altered (max-operator) much later, just before being stored), these things are now more centralized.
- While it was checked if individuals had been evaluated before, if two …
> Minor improvements

- tpot/metrics.py
Fixed division by zero error in metrics.py. Added one line of condition check.
[https://github.com/rhiever/tpot/blob/master/tpot/metrics.py#L50](url)
This is a small test file that tests and compare the functionality and output of the new and old balanced_accuracy function
[test.py.zip](https://github.com/rhiever/tpot/files/1069169/test.py.zip)
The issue is found by @KhaledSharif and followed up discussion are in that thread.
#493 
Result on [0, 1, 2, 3] and [0, 1, 2, 3]:
Original:
1.0
Fixed:
1.0
Result on [0, 1, 2, 3] and [1, 1, 2, 3]:
Original:
0.833333333333
Fixed:
0.833333333333
Result on [0, 1, 2, 3] and [1, 2, 3, 4]:
Original:
float division by zero
Fixed:
0.375
Ran 97 tests in 33.164s
OK
No
No
- Note …
> Fixed division by zero error in metrics.py

- tests/stacking_estimator_tests.py
- tests/tpot_tests.py
- tests/zero_count_tests.py
This PR just reorganizes unit tests of these built-in operators and move their unit tests out of `tpot_tests.py`.
> Reorganize unit tests for built-in operators

- tests/export_tests.py
- tests/tpot_tests.py
- tpot/base.py
- tpot/operator_utils.py
1. Fix a bug that "DEFAULT" in the parameter(s) of nested estimator causes `KeyError` when exporting pipeline, which is related to the issue #499 
2. Add a unit test for this issue
The [2 lines in `operator_utils.py`](https://github.com/rhiever/tpot/blob/v0.8/tpot/operator_utils.py#L229-L230) cause the bug in the issue #499. It works all right with operators without nested/stacked estimator as parameter(s) but it will cause `KeyError` once `dep_op_arguments` do not have nested/stacked estimator's name as key of the dictionary. It means that if any parameter is `DEFAULT` in the nested/stacked estimator would cause the whole pipeline cannot exported as valid scikit-learn Pipeline object.
> Removing "DEFAULT" value in terminals

- tests/tpot_tests.py
- tpot/base.py
1. If user passes CTRL+C when TPOT evaluating the initial population (generation 0), self._pareto_front will be empty so that `_update_top_pipeline` cannot update both self._optimized_pipeline and self.fitted_pipeline_. So it should raise a RuntimeError once self._pareto_front is empty.
2. add two unit tests for  `_update_top_pipeline` 
[`_update_top_pipeline` in base.py](https://github.com/weixuanfu2016/tpot/blob/2d6bb5cc8638f091b2f77ca54c1f53e83de24fb7/tpot/base.py#L586)
```
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data.astype(np.float64),
iris.target.astype(np.float64), train_size=0.75, test_size=0.25)
tpot = …
```
> rework _update_top_pipeline

- tests/tpot_tests.py
- tpot/base.py
1. Fix a bug in `self.set_param_recursive ` for setting "random_state" in nested estimator. The issue would happen with pipeline with `SelectFromModel` (`ExtraTreesClassifier` as nested estimator) or `StackingEstimator` if nested estimator has "random_state" as a parameter.
2. Add 3 unit tests for this `self.set_param_recursive` function.
[L867 in base.py](https://github.com/weixuanfu2016/tpot/blob/8f4572c3535254b6a0e5fc231aa6c8ae627850b1/tpot/base.py#L867)
Any TPOT example
- Do the docs need to be updated? No
- Does this PR add new (Python) dependencies? No
> Fix self.set_param_recursive for nested estimators

- tpot/gp_deap.py
moving to nanmean allows custom scorers that may return nan in certain situtations.
Solves a problem when scorers may return nan instead of a float
gp_deap.py 
[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]
> Moved GP to nanmean

- tests/tpot_tests.py
- tpot/base.py
- tpot/gp_deap.py
1. Refines _evaluate_individuals  to make `max_time_mins` can stop optimization during pipeline evaluation rather than at beginning of each generation.
2. Removes redundant codes in `cxOnePoint`
3. More unit tests for increasing code coverage.
> Refine_evaluate_individuals and more unit tests

- docs_sources/api.md
- docs_sources/using.md
- tests/driver_tests.py
- tests/tpot_tests.py
- tpot/base.py
- tpot/driver.py
1. refine `self._check_periodic_pipeline`
2. Add "early stopping" option for stopping optimization process when no improvement in a set number of generations
[base.py](https://github.com/weixuanfu/tpot/blob/ca19ca479cc2b68ce8f54ef97ea23955728eadeb/tpot/base.py#L837)
```
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import numpy as np
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data.astype(np.float64),
iris.target.astype(np.float64), train_size=0.75, test_size=0.25, random_state=42)
tpot = TPOTClassifier(generations=20, population_size=10, verbosity=2, early_stop=2, random_state=42)
tpot.fit(X_train, y_train)
```
#539 
- Do the docs need to be updated? Yes, docs were updated in the …
> Add "early stopping" option for stopping optimization process
