.landscape.yaml
README.md

This (landscape.io) is another really nice tool. In contrast to unit tests, it will evaluate your code for problems as well as style issues (e.g., unused imports). Highly recommended, plus it will add a "health" badge icon to your Readme similar to travis. You need to sign in at landscape.io with your github account in order to enable it.

monitor code health via landscape.io

---

.coveragerc
README.md

Adding coverage reports and badge via coveralls.io -- also here, you need to log in and enable the repo.
Plus, I added Python 2.7 and 3.5 version badges and a GPLv3 license badge.

Coveralls Coverage

---

tests.py
tpot/tpot.py

I added the docstrings to the public methods, please double-check if this is correct in its meaning :).
Also, I made the internal methods private so that a user is not confused when he/she calls help(TPOT)

Docstrings & Private Methods

---

tpot/tpot.py

Just saw that you had better, more informative descriptions of the init parameters in the Readme; added those to the docstrings.

More verbose docstrings

---

docs/mkdocs.yml
docs/sources/examples/Custom_Scoring_Functions.md
tpot/tpot.py

Per #33 , I've taken a stab at the arbitrary scoring function implementation, and wrote an example using scoring functions written in the same vein as the original balanced accuracy calculation.

Arbitrary scoring functions + doc example

---

tpot/tpot.py

minor readability stuff
just ignore the fact that github picks up whitespace here and there 
[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]
no
no

changes from abandoned cclauss pr

---

docs/sources/documentation/pipeline_operators/models/classifiers/ensemble/RandomForestClassifier.md
tests.py
tpot/export_utils.py
tpot/tpot.py

Remove n_estimators for the RF operator, per #119.
Other ensemble operators still need to have their n_estimators parameter removed and defaulted to some value.

RF operator rework

---

tests.py
tpot/tpot.py

Adds a new member function to the TPOT class that returns the inputted parameters of TPOT
`TPOT.get_params()`
A test was added for the get_params method, it can be seen in test_get_params in the tests.py module
#142

Add get_params function to TPOT to mimic the sklearn interface

---

tpot/export_utils.py

Fixes reference errors in the export_utils module
Exporting a pipeline containing a _gradient_boosting classifier
#167

Fix operator references in _gradient_boosting export code (Fixes #1

---

tpot/tpot.py

Rewrites the mutation function to store mutation techniques in a data structure for cleaner code
At the `_random_mutation_operator` function
Performing a fit() on TPOT

Refactor mutation function

---

.gitignore
tests.py
tpot/export_utils.py

Since it would be a bit unwieldy to test the exact export code of all exported functions I've added a test to at least run all of the branches of the `replace_function_calls` function to make sure they don't throw some kind of error.
`test_replace_function_calls_2()` in tests.py
Running nosetests
#179
#172

Add test for replace_function_calls and fix errors in the function (Fixed #179)

---

setup.py
tests.py
tpot/tpot.py

A quick prototype for MDR in TPOT 
def _mdr(self, input_df, tie_break, default_label, num_features_to_combined = 2, score = None):
Yet to be covered 
[you can link directly to issues by entering # then the number of the issue, for example, #3 links to issue 3]
Core implementation for MDR in TPOT

Core implementation for MDR in TPOT

---

tests.py
tpot/operators/base.py
tpot/operators/selectors/rfe.py
tpot/tpot.py

Adds some blocks to ignore warnings during calls to `fit()` for sklearn pipelines.

Ignore UserWarnings

---

tpot/driver.py

fix a case sensitivity file reader issue
go to the bug report, create the input file, run it. then make the one line change, run again, and voilà.
bug report has example to use
#259
- Do the docs need to be updated? NO
- Does this PR add new (Python) dependencies? NO

add case sensitive

---

tpot/_version.py
tpot/base.py

Small fix for checking if random_state is set, and documentation fix.

Fixed small problem when random_state = 0

---

tests.py
tpot/base.py
tpot/export_utils.py

Fix the bug in export function which cause that the output of TPOT included unused packages. 
Line 132 in export_utils.py
Tests are already included in unit tests
#309

Fix a bug causing importing unused package in TPOT output

---

tests.py
tpot/base.py

Exposes the predict_proba and predict_log_proba functions of the scikit-learn classifiers and regressers
https://github.com/rhiever/tpot/issues/276

Expose predict proba

---

tests.py
tpot/base.py

Revert "Expose predict proba"

---

tpot/base.py
tpot/operator_utils.py

Fix a issue related to some unavailable operators, like xgboost, in environment. 
Any TPOT example
mentioned in a comment of  #350

Add a warning for importing unavailable operator 

---

tpot/gp_deap.py

Fix a bug in varOR function based on issue #362

Fix a bug in varOR

---

setup.py
tests.py
tpot/decorators.py

A small edit in setup.py for adding required version of `scikit-learn` based on [Python Packaging User Guide](https://packaging.python.org/requirements/#install-requires-vs-requirements-files)
Also add unit test for timeout decorator.
[Only one line in setup.py](https://github.com/weixuanfu2016/tpot/blob/bf1f5b57f3344bc35abca6fde1da8c41fa718775/setup.py#L37)
Any TPOT examples
#348

Add version info in setup.py

---

tpot/base.py
tpot/gp_deap.py

Add a loop (50 times at most) to force mutation and crossover operator to generate a different individual in GP
varOr func in gp_deap.py
Any TPOT examples
#364

Force mutation and crossover operator to generate a different individual

---

tests.py

Fix score in a unit test

---

docs_sources/releases.md
docs_sources/using.md
tests.py
tpot/base.py
tpot/driver.py
tpot/operator_utils.py

* Add release note for version 0.7
* Change name of offspring size parameter from `-os` (confusing with OS) to `-c` (for child) and add descriptions about the parameter in online manual
* Add a unit test for `set_sample_weight` function

Add Release Note for Version 0.7

---

tpot/decorators.py
tpot/operator_utils.py

Fix bugs in issue #379 and #380

Fix bugs in issue 379 and 380

---

tpot/gp_deap.py

Just add sorted  based on the conversation in [issue 190 of deap repo](https://github.com/DEAP/deap/issues/190#issuecomment-292669574).

Add sorted type list in crossover

---

tests.py

refine 2 unit tests due to subsample param

refine 2 unit tests due to subsample param

---

tpot/base.py

Documentation in _evaluate_individuals

---

tests.py

Add 4 unit tests to increase code coverages.

Add 4 new unit tests

---

docs_sources/installing.md
optional-requirements.txt
setup.py

Add a note for xgboost version in installation.
Related issue: #466 #469

add doc for xgboost version issue

---

tests.py
tpot/export_utils.py

#484 
A quick patch for fixing a bug in export_utils.py mentioned in issue 484

A patch for fixing a bug in issue 484

---

tests.py

Add a unit test for issue #484

Add a unit test for issue 484

---

.appveyor.yml

Adds a config file to test TPOT on Windows via AppVeyor CI

Adds AppVeyor CI config for Windows

---

tests/tpot_tests.py
tpot/base.py

1. rework _evaluate_individuals for reducing duplicate codes
2. add _update_bar function for updating process bar and reducing duplicate codes
3. fix a small bug that pbar does not update the number of duplicate pipelines during pipeline evaluation. 
4. add 4 unit tests for these small functions and checks of warning messages from process bars.
[L893 in base.py](https://github.com/weixuanfu2016/tpot/blob/85d71da7b981e91537e158fe50772f293684e28a/tpot/base.py#L893)
Any TPOT examples
- Do the docs need to be updated? No
- Does this PR add new (Python) dependencies? No

rework _evaluate_individuals

---

tests/export_tests.py
tests/tpot_tests.py
tpot/base.py
tpot/export_utils.py

Adds an imputation step to exported pipeline code if feature values were imputed during GP.
In export_utils
I've added a test named `test_imputer_in_export` in the export tests file.
#511

Imputer in export

---

tests/tpot_tests.py
tpot/base.py
tpot/gp_deap.py

1. Add 2 unit tests for new crossover operator in dev branch for better code coverage. 
2. A little code cleaning.

Add 2 unit tests for new crossover operator in dev branch

---

tests/export_tests.py
tests/tpot_tests.py
tpot/base.py
tpot/decorators.py
tpot/export_utils.py

1. refine self._update_pbar for reducing redundant codes
2. More unit tests to increase code coverage.
3. Fix a bug in _save_pipeline_if_period and add 3 unit tests for this function

Refine _update_pbar and _save_pipeline_if_period and more unit tests
